#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

pushd $DIR

mkdir ~/Projects
mkdir ~/Downloads

docker run -dt \
  -v /etc/passwd:/etc/passwd \
  -v $PWD/smb.conf:/etc/samba/smb.conf \
  -v $HOME/Projects:/storage/Projects \
  -v $HOME/Downloads:/storage/Downloads \
  -p 445:445 \
  --name samba \
  --restart=always \
  stanback/alpine-samba

popd
